# config.yaml

experiment_name: "qaoa_test_suite"

problem:
  type: "MaxCut"

qaoa_parameters:
  p: 1
  initial_gamma: 0.5
  initial_beta: 0.5
  initial_theta: 0.5

alpha: 0.1

shots: 1024

hardware: False

noise: False

classical_optimizer: "minimize"

optimizer:
  name: "COBYLA"
  maxiter: 30

